version: '3'
services:
  api:
    container_name: find-here-pois-api
    build: .
    env_file:
      - .env
    volumes:
      - ./api:/opt/services/app/api
    ports:
      - "9000:9000"
  client:
    container_name: find-here-pois-client
    build:
      context: ./client
      dockerfile: Dockerfile.local
    ports:
      - "3000:3000"
